---
title: "Contrasting water use strategies revealed by species-specific transpiration dynamics in the Caatinga dry forest"
author: "Cynthia Wright"
date: "2023-12-04"
output: html_document
---

This repository contains the data used to create the results presented in the paper: [Contrasting water use strategies revealed by species-specific transpiration dynamics in the Caatinga dry forest](https://academic.oup.com/treephys/advance-article/doi/10.1093/treephys/tpad137/7342201?utm_source=advanceaccess&utm_campaign=treephys&utm_medium=email). The aim of this work is to better understand how the sap flux density of species with low vs. high wood densities differ in their sensitivity to vapor pressure deficit and soil water content, and how potentially opposing water use strategies influence transpiration dynamics and ultimately correlations to evapotranspiration. We use hysteresis area analysis to quantify the sensitivity of species-specific sap flux density to changes in vapor pressure deficit, breakpoint-based models to determine the soil water content threshold instigating a transpiration response, and multiscalar wavelet coherency to correlate transpiration to evapotranspiration.   

This is a draft version. 

The document structure is 
1. SF_Data: contains tree-level data
2. SF_Code: contains R code used to clean data and generate plots
3. SF_Figure: contains the output figure as a tiff

Please note that evapotranspiration data is not included in this repository, as it is owned by collaborators and has not been released to the public. 


